In [1]:
import pandas as pd
import numpy as np
import random
import copy

In [2]:
df = pd.read_csv("data.csv")

In [3]:
list_ws = [[1],[2,3],[4,5,6]]

##### Pengelompokkan

In [4]:
def make_kelompok(df):
    kelompok = []

    for i in range (0,len(df),5):
        kelompok.append(list(range(i,i+5)))
    return kelompok

In [5]:
list_kelompok = (make_kelompok(df))

In [6]:
list_kelompok

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29]]

In [7]:
def find_empty(df):
    empty = []
    for i in range (len(df)):
        # print(i)
        for j in range (len(df.iloc[i])):
            if pd.isna(df.iloc[i][j]):
                empty.append([i,j])
                
    return empty
print(find_empty(df))

list_empty = find_empty(df)

[[5, 0], [6, 0], [7, 0], [8, 0], [9, 0], [20, 0], [21, 0], [22, 0], [23, 0], [24, 0]]


In [8]:
def find_column_in_matrix(value, matrix):
    for i in range (len(matrix)):
        for j in range (len(matrix[i])):
            if (matrix[i][j] == value):
                return i

print(find_column_in_matrix(6, list_ws))

2


In [9]:
def routing(list_kelompok, empty):
    list_route = []
    for kelompok in list_kelompok:
        ws_list = [1,2,3]
        for job in kelompok:
            for unused_job, ws_num in empty:
                if (job == unused_job):
                    found = find_column_in_matrix(ws_num+1, list_ws)
                    if found+1 in ws_list:
                        ws_list.remove(found+1)
        list_route.append(ws_list)
    return list_route

list_routing = routing(list_kelompok, list_empty)
print(list_routing)

[[1, 2, 3], [2, 3], [1, 2, 3], [1, 2, 3], [2, 3], [1, 2, 3]]


In [10]:
def generate_waktu(df):
    list_waktu = []
    for kelompok in list_kelompok: 
        list_waktu_kelompok = []
        for task in range(df.shape[1]):
            sum = 0
            for job in kelompok:
                sum += df.iloc[job][task]
            if np.isnan(sum):
                sum = 0
            list_waktu_kelompok.append(sum)
        list_waktu.append(list_waktu_kelompok)
    return list_waktu
list_waktu = generate_waktu(df)
print(np.array(generate_waktu(df)))

def get_from_matrix(x,y):
    return list_waktu[x][y]

[[11. 18. 18.  8.  8.  8.]
 [ 0. 11. 11. 16. 16. 16.]
 [17. 19. 19. 16. 16. 16.]
 [18. 12. 12. 17. 17. 17.]
 [ 0. 15. 15. 15. 15. 15.]
 [12. 14. 14. 18. 18. 18.]]


#### Main Process Start Here
##### HYPER PARAMETER HERE


In [11]:
num_solution = 3
jumlah_mesin = 6
jumlah_kelompok = 6
crossover_rate = 0.25
mutation_rate = 0.1

total_gen = jumlah_mesin * num_solution
number_of_mutation = int(np.ceil(mutation_rate * total_gen))


r1 = random.randrange(1,total_gen)
r2 = random.randrange(1,total_gen)

r1 = 5
r2 = 9

r1,r2


(5, 9)

##### STEP 1. Generate Initial Population

In [12]:
def generate_step(job,operasi,mesin):
    dict = [job,operasi,mesin]
    return dict


def generate_first_solution(arr):
    step_collection = []
    for i in range (len(arr)):
        step = []
        for j in range (num_solution):
            step.append(generate_step(arr[i],j+1,list_ws[j][0]))
        step_collection.append(step)
    return(step_collection)

solution_collection = [
    generate_first_solution([1,2,3,4,5,6]),
    generate_first_solution([6,5,4,3,2,1]),
    generate_first_solution([4,5,6,1,2,3])
]

base = solution_collection.copy()

def display_solutions(second):
    for i in range (len(second)):
        for j in range (len(second[i])):
            print(second[i][j],end="\n")
        print("\n")
display_solutions(solution_collection)


[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




In [13]:
output_step_1 = solution_collection.copy()

(display_solutions(output_step_1))


[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




##### STEP 2. Evaluation

In [14]:
def evaluation(solution):
    current_step_mesin = np.zeros(jumlah_mesin)
    base_kelompok = np.zeros(jumlah_kelompok)

    def refine(i,j):
        return (solution[i][j][0]-1, solution[i][j][2]-1)

    for i in range (len(solution)):
        for j in range (len(solution[i])):
            feed_i, feed_j = refine(i,j)
            time_used = get_from_matrix(feed_i, feed_j)
            if (time_used != 0):
                # print(i+1,j+1,time_used)
                a = feed_i
                b = feed_j
                if (base_kelompok[a] >= current_step_mesin[b]):
                    current_step_mesin[b] = base_kelompok[a] + get_from_matrix(a,b)
                else:
                    current_step_mesin[b] += get_from_matrix(a,b)
                base_kelompok[a] = current_step_mesin[b]
                # print(base_kelompok)
                # print(current_step_mesin)
    #     print("=====")
    # print(np.max(current_step_mesin))
    return(np.max(current_step_mesin))
    

def step_2_evaluation(solution):
    # print(solution)
    # print(len(solution))
    return [evaluation(solution[0]), evaluation(solution[1]), evaluation(solution[2])]

output_step_2 = step_2_evaluation(solution_collection)
print(output_step_2)

[125.0, 116.0, 123.0]


In [15]:
solution_collection

[[[[1, 1, 1], [1, 2, 2], [1, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]],
  [[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[6, 1, 1], [6, 2, 2], [6, 3, 4]]],
 [[[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]]],
 [[[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]]]]

##### STEP 3. Selection

In [16]:
def generate_fitness(output):
    result = np.zeros(len(output))
    for i in range(len(output)):
        result[i] = 1/output[i]
    return result

def prob_every_chromosome(fitness):
    probabilities = np.zeros(len(fitness))
    combine_prob = np.zeros(len(fitness))

    sum_fitness = np.sum(fitness)
    sum_prob = 0
    
    for i in range(len(fitness)):
        probabilities[i] = fitness[i]/sum_fitness
        sum_prob += probabilities[i]
        combine_prob[i] =  sum_prob
    return probabilities, combine_prob

list_fitness = generate_fitness(output_step_2)
list_probabilities, list_combinatory = prob_every_chromosome(list_fitness)
print(list_probabilities,list_combinatory)



[0.32322225 0.34829984 0.3284779 ] [0.32322225 0.6715221  1.        ]


In [17]:
def random_number_generator(probabilities):
    randomized = np.zeros(len(probabilities))
    for i in range (len(probabilities)):
        randomized[i] = np.random.rand()
    return randomized

list_random = random_number_generator(list_probabilities)

list_random = [0.992, 0.422,0.962]
print(list_random)

[0.992, 0.422, 0.962]


In [18]:
def explain_matrix(matrix):
    for i in range (len(matrix)):
        for j in range (len(matrix[i])):
            print(matrix[i][j][0][0],end="")
        print("\n")

explain_matrix(base)

123456

654321

456123



In [19]:
def assign_combinatory_to_chromosome(list_random, list_combinatory, output_step_1):
    clone_output_step_1 = output_step_1.copy()
    for i in range (len(list_random)):
        if (list_random[i] < list_combinatory[0]):
            output_step_1[i] = clone_output_step_1[0]
        elif (list_random[i] >= list_combinatory[0] and list_random[i] < list_combinatory[1]):
            output_step_1[i] = clone_output_step_1[1]
        else:
            output_step_1[i] = clone_output_step_1[2]
            
    
    return output_step_1

output_step_3 = (assign_combinatory_to_chromosome(list_random, list_combinatory, output_step_1))
# print(output_step_3)

In [20]:
explain_matrix(output_step_3)

456123

654321

456123



##### STEP 4. Crossover

In [21]:
def process_3_crossover(output_step_3):
    kromosom1, kromosom2, kromosom3 = output_step_3
    
    formulate1 = []

    for index in range (len(kromosom1)):
        if (kromosom1[index] == kromosom2[index]):
            formulate1.append(kromosom1[index])
        else:
            formulate1.append(kromosom3[index])

    kromosom1, kromosom2, kromosom3 = kromosom2, kromosom3, kromosom1


    formulate2 = []

    for index in range (len(kromosom1)):
        if (kromosom1[index] == kromosom2[index]):
            formulate2.append(kromosom1[index])
        else:
            formulate2.append(kromosom3[index])

    kromosom1, kromosom2, kromosom3 = kromosom2, kromosom3, kromosom1


    formulate3 = []

    for index in range (len(kromosom1)):
        if (kromosom1[index] == kromosom2[index]):
            formulate3.append(kromosom1[index])
        else:
            formulate3.append(kromosom3[index])       

    return[formulate1, formulate2, formulate3]

# process_3_crossover()

In [22]:
def process_2_crossover(crossover_point,output_step_3):
    kromosom1, kromosom2, kromosom3 = output_step_3
    # print(output_step_1)
    
    formulate1 = kromosom1[:crossover_point+1] + kromosom2[crossover_point+1:]
    formulate2 = kromosom2[:crossover_point+1]+ kromosom1[crossover_point+1:]
    formulate3 = kromosom3
    return [formulate1, formulate2, formulate3]


# print(process_2_crossover(2))

In [23]:
def step_4_crossover(list_random_crossover,output_step_3):
    list_random_crossover = random_number_generator(list_probabilities)
    # list_random_crossover = [0.139161237267897, 0.140290355, 0.666743680741016]

    def calculate_crossover_points():
        count_crossover_points = 0
        for i in range (len(list_random_crossover)):
            if (list_random_crossover[i] <= crossover_rate):
                count_crossover_points += 1
        return count_crossover_points

    count_crossover_points = calculate_crossover_points()
    

    while count_crossover_points == 1:
        list_random_crossover = random_number_generator(list_probabilities)
        count_crossover_points = calculate_crossover_points()

    if (count_crossover_points == 3):
        return process_3_crossover(output_step_3)
    elif (count_crossover_points == 2):
        return process_2_crossover(2,output_step_3)
    else:
        return step_4_crossover(list_probabilities, output_step_3)


list_random_crossover = [0.139161237267897, 0.140290355, 0.666743680741016]
output_step_4 = step_4_crossover(list_random_crossover,output_step_3)
explain_matrix(output_step_4)

456321

654123

456123



##### STEP 5. Mutation

In [24]:
print(number_of_mutation)

2


In [25]:
output_step_4[r1//5]

[[[6, 1, 1], [6, 2, 2], [6, 3, 4]],
 [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
 [[4, 1, 1], [4, 2, 2], [4, 3, 4]],
 [[1, 1, 1], [1, 2, 2], [1, 3, 4]],
 [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
 [[3, 1, 1], [3, 2, 2], [3, 3, 4]]]

In [26]:
second = output_step_4.copy()
second

[[[[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]]],
 [[[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]]],
 [[[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]]]]

In [27]:
deep_copy = output_step_4.copy()

def mutation_process(deep_copy,array_value):
    for r_value in array_value:
        correspondence_machine = deep_copy[r_value//jumlah_mesin][r_value%jumlah_mesin -1]
        for i in range (len(correspondence_machine)):
            if (len(list_ws[i]) != 1):
                available = list_ws[i].copy()
                if (correspondence_machine[i][2] in available):
                    available.remove(correspondence_machine[i][2])
                correspondence_machine[i][2] = random.choice(available)
    # display_solutions(deep_copy)
    return deep_copy

def display_solutions(second):
    for i in range (len(second)):
        for j in range (len(second[i])):
            print(second[i][j],end="\n")
        print("\n")


In [28]:
def evaluation_step_5_after_randomized(step4,r1,r2):
    # print("CALLED")
    deep_copy = step4.copy()
    return mutation_process(deep_copy, [r1,r2])

output_step_5 = (evaluation_step_5_after_randomized(output_step_4,r1,r2))

In [29]:
solution_collection = [
    generate_first_solution([1,2,3,4,5,6]),
    generate_first_solution([6,5,4,3,2,1]),
    generate_first_solution([4,5,6,1,2,3])
]

display_solutions(solution_collection)

[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




In [30]:
display_solutions(output_step_5)

[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 3], [2, 3, 6]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 3], [4, 3, 6]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




##### STEP 6. EVALUATION

In [31]:

def step_6_evaluation(solution):
    # print(solution)
    return [evaluation(solution[0]), evaluation(solution[1]), evaluation(solution[2])]

output_step_6 = step_6_evaluation(output_step_5)

##### STEP 7. ELIMINATION

In [32]:
print(output_step_2)
print(output_step_6)

[125.0, 116.0, 123.0]
[104.0, 105.0, 123.0]


In [33]:
display_solutions(output_step_1)

[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 3], [4, 3, 6]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 3], [2, 3, 6]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




In [34]:
def elimination_step_7(solution_collection, output_step_2, output_step_6, output_step_4):
    
    dictionary = {}
    # print(base, output_step_2)
    # print(output_step_4, output_step_6)
    for i in range (len(output_step_1)):
        dictionary[output_step_2[i]] = solution_collection[i].copy()

    for i in range (len(output_step_4)):
        dictionary[output_step_6[i]] = output_step_4[i]

    # print(dictionary.keys())
    
    sorted_dict = dict(sorted(dictionary.items()))

    # arr = list(sorted_dict.values())
    # for i in range (len(arr)):
    #     print(arr[i])
    # print(sorted_dict.keys())
    # print(sorted_dict.values())

    return sorted_dict

    # first_n_combinations = list(itertools.islice(sorted_dict.items(), num_solution))
    # # sort_orders = sorted(dictionary.values(), key=lambda x: x[0], reverse=True)
    # print(first_n_combinations)
    # return first_n_combinations

new_solution = (elimination_step_7(solution_collection, output_step_2, output_step_6, output_step_4))

In [35]:
def display_solutions(second):
    for i in range (len(second)):
        for j in range (len(second[i])):
            print(second[i][j],end="\n")
        print("\n")
display_solutions(solution_collection)

[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




In [36]:
display_solutions(output_step_4)

[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]
[[2, 1, 1], [2, 2, 3], [2, 3, 6]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]


[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[4, 1, 1], [4, 2, 3], [4, 3, 6]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]


[[4, 1, 1], [4, 2, 2], [4, 3, 4]]
[[5, 1, 1], [5, 2, 2], [5, 3, 4]]
[[6, 1, 1], [6, 2, 2], [6, 3, 4]]
[[1, 1, 1], [1, 2, 2], [1, 3, 4]]
[[2, 1, 1], [2, 2, 2], [2, 3, 4]]
[[3, 1, 1], [3, 2, 2], [3, 3, 4]]




#### NEXT ITERATION CALLED HERE

In [37]:
new_solution_used = (list(new_solution.values())[:num_solution])

In [38]:
new_solution_used

[[[[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]],
  [[2, 1, 1], [2, 2, 3], [2, 3, 6]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]]],
 [[[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[4, 1, 1], [4, 2, 3], [4, 3, 6]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]]],
 [[[6, 1, 1], [6, 2, 2], [6, 3, 4]],
  [[5, 1, 1], [5, 2, 2], [5, 3, 4]],
  [[4, 1, 1], [4, 2, 2], [4, 3, 4]],
  [[3, 1, 1], [3, 2, 2], [3, 3, 4]],
  [[2, 1, 1], [2, 2, 2], [2, 3, 4]],
  [[1, 1, 1], [1, 2, 2], [1, 3, 4]]]]

In [69]:
num_solution = 3
jumlah_mesin = 6
jumlah_kelompok = 6
crossover_rate = 0.25
mutation_rate = 0.1

total_gen = jumlah_mesin * num_solution
number_of_mutation = int(np.ceil(mutation_rate * total_gen))

    
def iteration(num_of_iteration):
    for iteration in range ((num_of_iteration)):
        r1 = random.randrange(1,total_gen)
        r2 = random.randrange(1,total_gen)
        if (iteration == 0):
            solution_collection = [
                generate_first_solution([1,2,3,4,5,6]),
                generate_first_solution([6,5,4,3,2,1]),
                generate_first_solution([4,5,6,1,2,3])
            ]
        output_step_1 = solution_collection.copy()
        backup_solution = copy.deepcopy(solution_collection)
        output_step_2 = step_2_evaluation(output_step_1)
        list_fitness = generate_fitness(output_step_2)
        list_probabilities, list_combinatory = prob_every_chromosome(list_fitness)

        list_random = random_number_generator(list_probabilities)
        # list_random = [0.992, 0.422,0.962]

        output_step_3 = assign_combinatory_to_chromosome(list_random, list_combinatory, output_step_1)

        
        list_random_crossover = random_number_generator(list_probabilities)
        # list_random_crossover = [0.139161237267897, 0.140290355, 0.666743680741016]
        output_step_4 = step_4_crossover(list_random_crossover,output_step_3)

        # display_solutions(solution_collection)
        # display_solutions(backup)
        output_step_5 = (evaluation_step_5_after_randomized(output_step_4,r1,r2))

        # solution_collection = [
        #     generate_first_solution([1,2,3,4,5,6]),
        #     generate_first_solution([6,5,4,3,2,1]),
        #     generate_first_solution([4,5,6,1,2,3])
        # ]
        
        # display_solutions(solution_collection)
        # # print(r1,r2)
    
        output_step_6 = step_6_evaluation(output_step_5)
        # display_solutions(backup_solution)
        new_solution = (elimination_step_7(backup_solution, output_step_2, output_step_6, output_step_4))
        # display_solutions(output_step_2)
        new_solution_keys = (list(new_solution.keys())[:num_solution])
        new_solution_value = (list(new_solution.values())[:num_solution])
        print(new_solution_keys, list(new_solution.keys())[:])        
        solution_collection = new_solution_value

    return (solution_collection)

display_solutions(iteration(500))

    

[113.0, 116.0, 123.0] [113.0, 116.0, 123.0, 125.0]
[92.0, 113.0, 116.0] [92.0, 113.0, 116.0, 123.0]
[92.0, 98.0, 113.0] [92.0, 98.0, 113.0, 116.0]
[84.0, 92.0, 98.0] [84.0, 92.0, 98.0, 106.0, 113.0, 116.0]
[84.0, 92.0, 98.0] [84.0, 92.0, 98.0]
[84.0, 92.0, 98.0] [84.0, 92.0, 98.0, 103.0, 108.0]
[84.0, 92.0, 98.0] [84.0, 92.0, 98.0]
[84.0, 92.0, 98.0] [84.0, 92.0, 98.0]
[84.0, 90.0, 92.0] [84.0, 90.0, 92.0, 98.0]
[84.0, 90.0, 92.0] [84.0, 90.0, 92.0, 98.0]
[84.0, 90.0, 92.0] [84.0, 90.0, 92.0]
[84.0, 90.0, 92.0] [84.0, 90.0, 92.0]
[84.0, 90.0, 92.0] [84.0, 90.0, 92.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 92.0, 103.0, 109.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 98.0, 103.0, 104.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 92.0, 98.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 92.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 98.0, 105.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0, 92.0, 98.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0]
[84.0, 88.0, 90.0] [84.0, 88.0, 90.0]
[